services:
  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: todo_backend
    ports:
     - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/todo_db
    depends_on:
      - db
    volumes:
      - ./backend:/app
      # ホストマウントによるnode_modulesの上書き防止
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: todo_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # バックエンドコンテナへの接続URL（コンテナ間通信）
      - BACKEND_URL=http://backend:3001
    depends_on:
      - backend
# DockerVolumeへ
volumes:
  postgres_data: